### ISSUE TITLE
Survey is not displaying when we send the survey event.

### ISSUE THREAD

**Issue by Avikal-Jain** [iteratehq/iterate-android#93] opened 2024-09-28 19:11 UTC
The survey is not displaying when we send the survey event **(Iterate.sendEvent("viewed-activity-feed", supportFragmentManager, eventTraits()))** and switch from Activity A to Activity B. We are encountering the following exception in the Iterate SDK:

 **java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1852)
 androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1892)
androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:341)
androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:306)
androidx.fragment.app.DialogFragment.show(DialogFragment.java:502)
com.iteratehq.iterate.Iterate.showSurvey(Iterate.kt:300)
com.iteratehq.iterate.Iterate.showSurveyOrPrompt(Iterate.kt:276)
com.iteratehq.iterate.Iterate.access$showSurveyOrPrompt(Iterate.kt:35)
com.iteratehq.iterate.Iterate$sendEvent$2$onSuccess$3$1.invokeSuspend(Iterate.kt:211)
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)**

Please provide a solution or address this issue as soon as possible.

**Comment by lankybutmacho** [comment] 2024-10-15 14:46
Hi, thanks for this report. The issue is fixed in 1.4.1.

**Closed by lankybutmacho** 2024-10-15 14:46 UTC
