### ISSUE TITLE
Crash due to EncryptedSharedPreferences when upgrading from one phone to another

### ISSUE THREAD

**Issue by sqawwas** [iteratehq/iterate-android#56] opened 2022-11-22 16:46 UTC
See the following crash when attempting to open our app using the Iterate SDK if a person upgraded from one phone to another (example Pixel 6 to Pixel 7) copying the app over through transfer tools. 

The crash seems to be caused by Iterate attempting to create a new EncryptedSharedPrefences when one already exists. We'd prefer not to have to turn off EncryptedSharedPrefences in not necessary.

```
2022-11-22 09:58:53.395 22365-22365/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.reveltransit, PID: 22365
    java.lang.RuntimeException: Unable to create application com.reveltransit.App: com.google.crypto.tink.shaded.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6717)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: com.google.crypto.tink.shaded.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
        at com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite.parsePartialFrom(GeneratedMessageLite.java:1566)
        at com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite.parseFrom(GeneratedMessageLite.java:1664)
        at com.google.crypto.tink.proto.Keyset.parseFrom(Keyset.java:957)
        at com.google.crypto.tink.integration.android.SharedPrefKeysetReader.read(SharedPrefKeysetReader.java:84)
        at com.google.crypto.tink.CleartextKeysetHandle.read(CleartextKeysetHandle.java:58)
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.read(AndroidKeysetManager.java:328)
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readOrGenerateNewKeyset(AndroidKeysetManager.java:287)
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(AndroidKeysetManager.java:238)
        at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:155)
        at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:120)
        at com.iteratehq.iterate.data.local.DefaultIterateSharedPrefs$prefs$2.invoke(IterateSharedPrefs.kt:31)
        at com.iteratehq.iterate.data.local.DefaultIterateSharedPrefs$prefs$2.invoke(IterateSharedPrefs.kt:26)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.iteratehq.iterate.data.local.DefaultIterateSharedPrefs.getPrefs(IterateSharedPrefs.kt:26)
        at com.iteratehq.iterate.data.local.DefaultIterateSharedPrefs.getUserAuthToken(IterateSharedPrefs.kt:58)
        at com.iteratehq.iterate.data.DefaultIterateRepository.getUserAuthToken(IterateRepository.kt:92)
        at com.iteratehq.iterate.Iterate.initAuthToken(Iterate.kt:249)
        at com.iteratehq.iterate.Iterate.init(Iterate.kt:63)
        at com.iteratehq.iterate.Iterate.init$default(Iterate.kt:50)
        at com.reveltransit.App.initIterate(App.kt:175)
        at com.reveltransit.App.configure(App.kt:109)
        at com.reveltransit.App.onCreate(App.kt:57)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6712)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```

**Comment by Daphne-CoffeeIT** [comment] 2022-12-21 08:44
Same issue here. We're currently thinking of (temporarily) disabling Iterate until this gets fixed, since more and more users seem to be impacted. I hope it can be fixed soon!

**Comment by lankybutmacho** [comment] 2022-12-22 20:42
Thanks for your patience on this issue. This crash appears to be caused by a [known issue](https://github.com/google/tink/issues/504) in `com.google.crypto.tink`, to which there is not yet a definitive solution.

The only workaround we currently have available is to temporarily use the unencrypted SharedPreferences instead of EncryptedSharedPreferences by initializing Iterate with the `useEncryptedSharedPreferences = false` parameter as shown below.

```Kotlin
Iterate.init(this, API_KEY, useEncryptedSharedPreferences = false)
```

See [this comment](https://github.com/google/tink/issues/504#issuecomment-856527345) on that issue for context on why unencrypted SharedPreferences is secure enough in most cases.

**Comment by VincentTe** [comment] 2023-02-16 08:54
Is this still the only workaround? I currently have this issue in production for some user and I'm able to reproduce this by transferring app with the transfer tool, same as @sqawwas described. 

Right now I'm using the EncryptedSharedPref like this:

```kotlin
private val masterKeysAlias: String = MasterKeys.getOrCreate(MasterKeys.AES256_GCM_SPEC)
private val encryptedSharedPref = EncryptedSharedPreferences.create(
        CS_PREFERENCES,
        masterKeysAlias,
        context,
        EncryptedSharedPreferences.PrefKeyEncryptionScheme.AES256_SIV,
        EncryptedSharedPreferences.PrefValueEncryptionScheme.AES256_GCM
    )
```
How do I handle this InvalidProtocolBufferException here?

**Closed** 2024-01-16 21:37 UTC
